"use strict";
exports.__esModule = true;
exports.service = exports.date = exports.email = exports.name = exports.licensePlate = exports.phoneNumber = exports.alphanumeric = exports.numeric = exports.exists = void 0;
var luxon_1 = require("luxon");
var exists = function (data) { return data !== null && data !== undefined && data !== ""; };
exports.exists = exists;
var numberExp = /^[\d]+$/;
var numeric = function (data) { return numberExp.test(data); };
exports.numeric = numeric;
var alphaNumericExp = /^\w+$/;
var alphanumeric = function (data) { return alphaNumericExp.test(data); };
exports.alphanumeric = alphanumeric;
var phoneExp = /^ *\(?\d{3} *\)? *[\.|-]? *\d{3} *[\.|-]? *\d{4} *$/;
var phoneNumber = function (data) { return phoneExp.test(data); };
exports.phoneNumber = phoneNumber;
var licensePlateExp = /^\w+ *-? *\w*$/;
var licensePlate = function (data) { return licensePlateExp.test(data); };
exports.licensePlate = licensePlate;
var nameExp = /^[\w,\.\- ]+$/;
var name = function (data) { return nameExp.test(data); };
exports.name = name;
var emailExp = /^.{1,}@.{1,}\..{1,}$/;
var email = function (data) { return emailExp.test(data); };
exports.email = email;
var date = function (data) {
    var d = luxon_1.DateTime.fromISO(data);
    return d.invalidReason ? false : true;
};
exports.date = date;
var serviceExp = /^[\w,\.\- ]+$/;
var service = function (data) { return serviceExp.test(data); };
exports.service = service;
