/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 2twh3DGwfm8NCFLvTkgxWhtoToVsFHsVRyZ2+WAdrXf0SThpwdSGO56bK96tTOVrPLK4oolqLKd0bc9X3uWcEg==
 */

/* eslint-disable */
// tslint:disable

interface BugReports {
  app_state: any
  /**
   * @default now()
   */
  created_at: Date
  id: string & {readonly __brand?: 'bug_reports_id'}
  message: string
  user_id: string
}
export default BugReports;

interface BugReports_InsertParameters {
  app_state: any
  /**
   * @default now()
   */
  created_at?: Date
  id: string & {readonly __brand?: 'bug_reports_id'}
  message: string
  user_id: string
}
export type {BugReports_InsertParameters}
