/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8JaC18ICXGxOmXqu13wcIY7/ZBNhlEaPS0E4Ae/aTtC3EDcIh8MXUEPiH4+NWFs6O2z1F5RY1Y94MdzrAQmptg==
 */

/* eslint-disable */
// tslint:disable

import BugReports, {BugReports_InsertParameters} from './bug_reports'
import FlywaySchemaHistory, {FlywaySchemaHistory_InsertParameters} from './flyway_schema_history'

interface DatabaseSchema {
  bug_reports: {record: BugReports, insert: BugReports_InsertParameters};
  flyway_schema_history: {record: FlywaySchemaHistory, insert: FlywaySchemaHistory_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "bug_reports" && c === "app_state") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}
